#!/bin/bash
# Get the project
git clone --recursive https://github.com/indigo-dc/tosca-parser.git

# Start installation
cd tosca-parser
sudo python setup.py install

# Store git project info
cat >> /tmp/tosca-to-hot.log << EOT
############################
#   TOSCA PARSER GIT INFO  #
############################
EOT
git log | head -n 3 >> /tmp/tosca-to-hot.log

cd toscaparser/tests/data/indigo/
cat >> /tmp/tosca-to-hot.log << EOT
############################
#   TOSCA TYPES GIT INFO   #
############################
EOT
git log | head -n 3 >> /tmp/tosca-to-hot.log


