#!/bin/bash
# Get the project
git clone https://github.com/openstack/heat-translator.git

# Start installation
cd heat-translator
sudo python setup.py install

# Show git project info
cat >> /tmp/tosca-to-hot.log << EOT
############################
# HEAT-TRANSLATOR GIT INFO #
############################
EOT
git log | head -n 3 >> /tmp/tosca-to-hot.log
