#!/bin/bash
# Install all the required dependencies
apt-get update
apt-get install -y linux-image-generic-lts-trusty
apt-get install -y git
apt-get install -y python python-setuptools python-pbr python-six python-yaml python-requests python-dateutil

# Install testing libs
git clone https://github.com/sstephenson/bats.git
cd bats/
./install.sh /usr/local
