#!/bin/bash
apt-get update
apt-get install -y linux-image-generic-lts-trusty
apt-get install -y git
apt-get install -y python python-setuptools python-pbr python-six python-yaml python-requests python-dateutil
